### ISSUE TITLE
id属性の重複

### ISSUE THREAD

**Issue by DevGosugi** [JhonFuji/PBL_Team6#14]
下記でid属性が重複しています。
- https://github.com/JhonFuji/PBL_Team6/blob/2d105b436e5cb10d7812a7de695ddc643db15679/spring-boot-PBL-team6/src/main/resources/templates/user/index.html#L626
- https://github.com/JhonFuji/PBL_Team6/blob/2d105b436e5cb10d7812a7de695ddc643db15679/spring-boot-PBL-team6/src/main/resources/templates/user/index.html#L649

**Comment by Edward-YY** [comment]
間違いました。target4にするつもりでした。
